### ISSUE TITLE
请教下loss计算时是如何考虑padding部分的呢？

### ISSUE THREAD

**Issue by boredtylin** [gaohongkui/GlobalPointer_pytorch#14]
batch内序列肯定有padding的，这部分好像在loss func里没有看到有处理的。

**Comment by gaohongkui** [comment]
序列内 padding 的去除在这里：
https://github.com/gaohongkui/GlobalPointer_pytorch/blob/d32f84b423c787d07ad4092ad0a922dc594987fb/models/GlobalPointer.py#L200
