### ISSUE TITLE
请问gp 算logits的时候 最后为什么要 开方？

### ISSUE THREAD

**Issue by CheungZeeCn** [gaohongkui/GlobalPointer_pytorch#18]
https://github.com/gaohongkui/GlobalPointer_pytorch/blob/d32f84b423c787d07ad4092ad0a922dc594987fb/models/GlobalPointer.py#L208

谢谢

**Comment by CheungZeeCn** [comment]
好像是 dot scaled attn  缘故 ？

**Comment by gaohongkui** [comment]
是的，参考的 Self-Attention 计算方式

**Comment by CheungZeeCn** [comment]
谢谢~
