### ISSUE TITLE
loss的参数顺序需要修正

### ISSUE THREAD

**Issue by DarthZhu** [gaohongkui/GlobalPointer_pytorch#25]
调用multilabel_categorical_crossentropy时出错：train.py / line 188
![image](https://user-images.githubusercontent.com/57787501/221418815-00d469b6-d51f-4f9b-8910-2db7a72aa711.png)
调用loss_fun出错：train.py / line 159
![image](https://user-images.githubusercontent.com/57787501/221419606-7cde4850-c5e2-4e32-b131-16a06c2bebbc.png)
loss计算在整体上没有问题，但是是因为后面参数传递也发生了错误。

**Comment by gaohongkui** [comment]
非常感谢你的 issue，最近的代码已将这部分参数逻辑统一
