### ISSUE TITLE
train.py中为啥每个epoch都要重新定义optimizer？

### ISSUE THREAD

**Issue by alkaideemo** [gaohongkui/GlobalPointer_pytorch#7]
https://github.com/gaohongkui/GlobalPointer_pytorch/blob/357906657ef318f8b55b94fa34fcfcd6b978b321/train.py#L267-L268
从这处代码看，每个epoch都会用一个新的optimizer和初始learning_rate训练model，和一般训练方案不太一样，这是作者大佬的什么trick吗？

**Comment by gaohongkui** [comment]
这是个Bug，不是Trick。😳😳😳
